
<?php

// $post_data = $this->getRequest()->getPostValue();

//  $order_id = $post_data['order_id'];
//  $blockObj= $block->getLayout()->createBlock('Mageget\OrderTracking\Block\OrderDetails');
//  $orderData = $blockObj->getOrderData($order_id);
//  foreach($orderData as $order) {
// 	 echo "<pre>";
// 	 print_r($order->getData());
//  }
 

//  $orderblockObj= $block->getLayout()->createBlock('Mageget\OrderTracking\Block\Order');
//  $orderData1 = $orderblockObj->getOrderCollection(000000046);
//  foreach($orderData1 as $order1) {
// 	 echo "<pre>";
// 	 print_r($order1->getData());
//  }










?>

<div class="container">
  <div class="track-flex-row">
						<div class="track-area">
							<div class="justify-content-between">
								<div class="order-tracking completed">
									<span class="is-complete"></span>
									<p>Ordered<br><span>Mon, June 24</span></p>
								</div>
								<div class="order-tracking completed">
									<span class="is-complete"></span>
									<p>Shipped<br><span>Tue, June 25</span></p>
								</div>
								<div class="order-tracking">
									<span class="is-complete"></span>
									<p>Delivered<br><span>Fri, June 28</span></p>
								</div>
							</div>
						</div>
					</div>
</div> 




<!-- 

Array
(
    [item_id] => 59
    [order_id] => 46
    [parent_item_id] => 
    [quote_item_id] => 95
    [store_id] => 1
    [created_at] => 2022-10-12 17:42:20
    [updated_at] => 2022-10-12 17:42:20
    [product_id] => 15
    [product_type] => simple
    [product_options] => Array
        (
            [info_buyRequest] => Array
                (
                    [uenc] => aHR0cDovL2xvY2FsaG9zdC9tYWdlbnRvMi9sYXB0b3AuaHRtbA,,
                    [product] => 15
                    [qty] => 1
                )

        )

    [weight] => 
    [is_virtual] => 0
    [sku] => HP Pavilion Gaming 15-ec2008AX
    [name] => HP Pavilion Gaming 15-ec2008AX (AMD Ryzen 5 5600H Processor/ 8 GB RAM / 512 GB SSD / 15.6" FHD Display / 4 GB NVIDIA Graphics / Win 10 / MSO)
    [description] => 
    [applied_rule_ids] => 
    [additional_data] => 
    [is_qty_decimal] => 0
    [no_discount] => 0
    [qty_backordered] => 
    [qty_canceled] => 0.0000
    [qty_invoiced] => 0.0000
    [qty_ordered] => 2.0000
    [qty_refunded] => 0.0000
    [qty_shipped] => 0.0000
    [base_cost] => 
    [price] => 400.0000
    [base_price] => 400.0000
    [original_price] => 400.0000
    [base_original_price] => 400.0000
    [tax_percent] => 0.0000
    [tax_amount] => 0.0000
    [base_tax_amount] => 0.0000
    [tax_invoiced] => 0.0000
    [base_tax_invoiced] => 0.0000
    [discount_percent] => 0.0000
    [discount_amount] => 0.0000
    [base_discount_amount] => 0.0000
    [discount_invoiced] => 0.0000
    [base_discount_invoiced] => 0.0000
    [amount_refunded] => 0.0000
    [base_amount_refunded] => 0.0000
    [row_total] => 800.0000
    [base_row_total] => 800.0000
    [row_invoiced] => 0.0000
    [base_row_invoiced] => 0.0000
    [row_weight] => 0.0000
    [base_tax_before_discount] => 
    [tax_before_discount] => 
    [ext_order_item_id] => 
    [locked_do_invoice] => 
    [locked_do_ship] => 
    [price_incl_tax] => 400.0000
    [base_price_incl_tax] => 400.0000
    [row_total_incl_tax] => 800.0000
    [base_row_total_incl_tax] => 800.0000
    [discount_tax_compensation_amount] => 0.0000
    [base_discount_tax_compensation_amount] => 0.0000
    [discount_tax_compensation_invoiced] => 
    [base_discount_tax_compensation_invoiced] => 
    [discount_tax_compensation_refunded] => 
    [base_discount_tax_compensation_refunded] => 
    [tax_canceled] => 
    [discount_tax_compensation_canceled] => 
    [tax_refunded] => 
    [base_tax_refunded] => 
    [discount_refunded] => 
    [base_discount_refunded] => 
    [gift_message_id] => 
    [gift_message_available] => 
    [free_shipping] => 0
    [weee_tax_applied] => 
    [weee_tax_applied_amount] => 
    [weee_tax_applied_row_amount] => 
    [weee_tax_disposition] => 
    [weee_tax_row_disposition] => 
    [base_weee_tax_applied_amount] => 
    [base_weee_tax_applied_row_amnt] => 
    [base_weee_tax_disposition] => 
    [base_weee_tax_row_disposition] => 
) -->
